[package]
name = "physics-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
cosmology = "0.3.2"
nalgebra = "0.33.2"
physical_constants = "0.5.0"
rustacuda = "=0.1.3"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
